### ISSUE TITLE
Could not find a file named "plugins/flutter_plugins/path_provider_fde/pubspec.yaml"

### ISSUE THREAD

**Issue by ka6tk** [google/flutter-desktop-embedding#625]
as mentioned in the repo. [dev.pup](https://pub.dev/packages/device_preview) , I have added the dependencies as below

```yaml
device_preview:
path_provider_fde:
  git:
    url: https://github.com/google/flutter-desktop-embedding/
    path: plugins/flutter_plugins/path_provider_fde
``` 

I am getting the the error like this

```
Could not find a file named "plugins/flutter_plugins/path_provider_fde/pubspec.yaml" in https://github.com/google/flutter-desktop-embedding/ b0ecf3dbbb2c75d55d2c0865e6fd9b529844e8c3.
pub get failed (1; Could not find a file named "plugins/flutter_plugins/path_provider_fde/pubspec.yaml" in https://github.com/google/flutter-desktop-embedding/ b0ecf3dbbb2c75d55d2c0865e6fd9b529844e8c3.)
exit code 1
```

**Comment by ka6tk** [comment]
```yml
url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      path: plugins/flutter_plugins/url_launcher_fde/
```
I made the above changes and started working,Thanks
