### ISSUE TITLE
Some fonts not rendering correctly on Windows

### ISSUE THREAD

**Issue by esDotDev** [google/flutter-desktop-embedding#709]
On Windows the font Quicksand-Bold just never seems to render. Here's Web on top, and Windows on the bottom:
![image](https://user-images.githubusercontent.com/736973/78294578-d7805280-74e7-11ea-94e4-b722800380ac.png)
```
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
```
https://fonts.google.com/specimen/Quicksand
