### ISSUE TITLE
Recommended 'file_selector' plugin does not appear to support Windows

### ISSUE THREAD

**Issue by esDotDev** [google/flutter-desktop-embedding#831]
This README instructs us to switch to file_selector https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_selector/README.md.

After doing so we're seeing MissingPluginException on Windows. 

Is this expected? If so, maybe the README could be updated to clarify this. It costs us a couple precious hours as we switched over, and now apparently need to switch back.

**Comment by stuartmorgan** [comment]
The unendorsed Windows implementation does in fact support Windows. Did you follow the instructions in the README that you linked to? Please provide your pubspec.yaml.

**Comment by esDotDev** [comment]
Thanks Stuart, I missed that last line, and when looking for an example in the linked repo didn't find any. I didn't realize there was still an implementation example here. 

For anyone else who stumbles on it, you want to use this:
```
file_selector_platform_interface: ^1.0.2
  file_selector_linux:
    path: ../file_selector_linux
  file_selector_macos:
    path: ../file_selector_macos
  file_selector_windows:
    path: ../file_selector_windows
```
from here: https://github.com/google/flutter-desktop-embedding/tree/master/plugins/file_selector/example
