### ISSUE TITLE
window_size null-safety

### ISSUE THREAD

**Issue by alizera** [google/flutter-desktop-embedding#869]
As I've updated flutter-SDK to v2 and fix a lot of issues, I faced with error that is saying `window_size` is not null-safe.

I added it via:
```
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 927f8cbc09b35d85245c095f2db8df9b186f6618
```
